add_newline = false

format = """
[╭─](white)$username$hostname in \
    $directory\
    $python\
    $c\
    $nodejs\
    $dotnet\
    $git_branch\
    $git_metrics\
    $cmd_duration
[╰─](white)$character """

[username]
show_always = true
style_root = "bold red"
style_user = "blue"
format = "[$user]($style) "
disabled = false

[hostname]
ssh_only = false
format =  "on [$hostname](dimmed blue)"
disabled = false

[directory]
style = "bold cyan"
read_only_style = "bold red"
truncation_length = 8
truncation_symbol = "…/"
format = "[$read_only]($read_only_style)[$path]($style) "
disabled = false

[c]
symbol = " "
style = "bold blue"
format = "[${symbol}${version}]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "[${symbol}${version}${virtualenv}]($style) "

[nodejs]
symbol = " "
style = "bold yellow"
format = "[${symbol}${version}]($style) "

[dotnet]
symbol = " "
style = "bold purple"
format = "[${symbol}${version}]($style) "


[git_branch]
symbol = " "
disabled = true

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false

[cmd_duration]
show_milliseconds = true
style = "bold green"
format = "took [$duration]($style)"

[character]
format = "$symbol"
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[❮](bold green)"
disabled = false

